-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        border_size = 2,
    },
})

-- Monitors
hl.monitor({
    output = "HDMI-A-2",
    disabled = false,
    mode = "1440x900@74.98Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
